In [1]:
import random
from JetDataset import JetDataset
import torch
from torch.utils.data import Dataset, DataLoader

In [18]:
train_dataset = JetDataset("../../data/val/val_20_30_new.h5", config=None)

Initializing JetDataset with file: ../../data/val/val_20_30_new.h5
Loading features and subjets from HDF5 file
Filtered to 261239 good jets
Final dataset size: 261239 jets


In [20]:
train_loader = DataLoader(train_dataset, batch_size=1000, shuffle=True)
train_iter = iter(train_loader)
while True:
    x, particle_features, subjets, particle_indices, subjet_mask, particle_mask = next(train_iter)

IndexError: index 128 is out of bounds for dimension 0 with size 128

In [17]:
print("x", x.shape) #(batch_size, N_subjets, N_part, N_part_ftr), dim 3 ordering: ['part_deta', 'part_dphi', 'part_pt_log', 'part_e_log']
print("particle features", particle_features.shape)
print("subjets", subjets.shape) # dim 2 ordering: ['subjet_pt', 'subjet_eta', 'subjet_phi', 'subjet_E, 'subjet_num_ptcls']
print("particle indices", particle_indices.shape)
print("subjet_mask", subjet_mask.shape)
print("particle_mask", particle_mask.shape)

x torch.Size([100, 20, 30, 4])
particle features torch.Size([100, 128, 4])
subjets torch.Size([100, 20, 5])
particle indices torch.Size([100, 20, 30])
subjet_mask torch.Size([100, 20])
particle_mask torch.Size([100, 20, 30])


## Check to see if x was constructed correctly

In [5]:
for jet_idx in range(10):
    for subjet_idx in range(20):
        num_real_ptcls = int(subjets[jet_idx, subjet_idx, -1])
        particle_features_at_subjet_idx = torch.zeros((30, 4))
        real_indices = particle_indices[jet_idx, subjet_idx].long()[:num_real_ptcls]
        particle_features_at_subjet_idx[:num_real_ptcls, :] = particle_features[jet_idx, real_indices, :]
        print((particle_features_at_subjet_idx == x[jet_idx, subjet_idx]).all())

tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)

In [6]:
particle_indices[0, subjet_idx]

tensor([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1.], dtype=torch.float64)

In [7]:
particle_features_at_subjet_idx.shape

torch.Size([30, 4])

In [8]:
particle_features_at_subjet_idx == x[0, subjet_idx]

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True,

In [9]:
x[0, 0]

tensor([[-0.0756,  6.1523,  4.7911,  4.9983],
        [-0.1000,  6.0422,  3.1591,  3.3523],
        [-0.0758,  6.0386,  2.9675,  3.1746],
        [-0.1024,  6.0335,  2.9542,  3.1460],
        [-0.1137,  6.0311,  2.6393,  2.8248],
        [-0.1269,  6.0305,  2.5899,  2.7681],
        [-0.1048,  6.0437,  2.5067,  2.6972],
        [-0.0239,  6.0109,  2.4144,  2.6526],
        [-0.0998,  6.0352,  2.2614,  2.4546],
        [ 0.0075,  6.1512,  1.6976,  1.9553],
        [ 0.1050,  6.0568,  1.2051,  1.5275],
        [ 0.1267,  5.9458,  0.8836,  1.2211],
        [-0.0646,  5.9976,  0.8666,  1.0802],
        [ 0.0150,  5.8787,  0.7136,  0.9762],
        [-0.0605,  5.8903,  0.6450,  0.8610],
        [-0.1794,  6.1206, -0.3119, -0.1615],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000

In [10]:
jet_idx = 1
subjet_idx = 1
num_real_ptcls = int(subjets[jet_idx, subjet_idx, -1])
particle_features_at_subjet_idx = torch.zeros((30, 4))
particle_features_at_subjet_idx[:num_real_ptcls] = particle_features[jet_idx, particle_indices[jet_idx, subjet_idx].long()[:num_real_ptcls], :]
particle_features_at_subjet_idx

tensor([[ 2.5191e-02, -2.6025e-01,  4.3913e+00,  5.0848e+00],
        [ 4.8948e-02, -2.4499e-01,  3.1821e+00,  3.8962e+00],
        [ 2.4684e-02, -1.8103e-01,  2.8751e+00,  3.5681e+00],
        [ 6.9477e-02, -3.8943e-01,  2.6219e+00,  3.3539e+00],
        [ 7.2018e-02, -1.7780e-01,  2.4344e+00,  3.1687e+00],
        [-2.1879e-02, -3.6831e-01,  1.6490e+00,  2.3020e+00],
        [ 2.4684e-02, -1.8103e-01,  1.6165e+00,  2.3096e+00],
        [ 6.1788e-02, -3.2459e-01,  8.9850e-01,  1.6239e+00],
        [ 1.6054e-01, -1.7279e-01,  8.1810e-01,  1.6309e+00],
        [-5.0352e-03, -1.7450e-01,  6.7175e-01,  1.3392e+00],
        [ 3.7771e-02, -2.2247e-01,  4.6225e-01,  1.1667e+00],
        [-7.6687e-03, -2.3487e-01,  1.2529e-01,  7.9046e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        

In [11]:
x[jet_idx, subjet_idx]

tensor([[ 2.5191e-02, -2.6025e-01,  4.3913e+00,  5.0848e+00],
        [ 4.8948e-02, -2.4499e-01,  3.1821e+00,  3.8962e+00],
        [ 2.4684e-02, -1.8103e-01,  2.8751e+00,  3.5681e+00],
        [ 6.9477e-02, -3.8943e-01,  2.6219e+00,  3.3539e+00],
        [ 7.2018e-02, -1.7780e-01,  2.4344e+00,  3.1687e+00],
        [-2.1879e-02, -3.6831e-01,  1.6490e+00,  2.3020e+00],
        [ 2.4684e-02, -1.8103e-01,  1.6165e+00,  2.3096e+00],
        [ 6.1788e-02, -3.2459e-01,  8.9850e-01,  1.6239e+00],
        [ 1.6054e-01, -1.7279e-01,  8.1810e-01,  1.6309e+00],
        [-5.0352e-03, -1.7450e-01,  6.7175e-01,  1.3392e+00],
        [ 3.7771e-02, -2.2247e-01,  4.6225e-01,  1.1667e+00],
        [-7.6687e-03, -2.3487e-01,  1.2529e-01,  7.9046e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        

In [12]:
subjets[jet_idx, subjet_idx, -1]

tensor(12., dtype=torch.float64)